# Generated by Django 5.1.5 on 2025-02-09 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="categorie",
            field=models.CharField(default="General", max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="post",
            name="frequence",
            field=models.TextField(default="General", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="post",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
