# Generated by Django 5.1.5 on 2025-02-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_categorie_post_frequence_alter_post_created_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="frequence",
            field=models.CharField(max_length=50),
        ),
    ]
